name: sayilar
description: An app with simple exercises for practicing turkish numbers.
homepage: https://github.com/JimGerth/sayilar-flutter
repository: https://github.com/JimGerth/sayilar-flutter
issue_tracker: https://github.com/JimGerth/sayilar-flutter/issues

publish_to: 'none'

version: 0.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^9.1.2
  normal: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0

flutter:
  generate: true
  uses-material-design: true

import_sorter:
  comments: false
